/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as IndexImport } from "./routes/index"
import { Route as FoodsFoodIdImport } from "./routes/foods.$foodId"

// Create Virtual Routes

const RecipesLazyImport = createFileRoute("/recipes")()
const DiaryLazyImport = createFileRoute("/diary")()
const FoodsIndexLazyImport = createFileRoute("/foods/")()

// Create/Update Routes

const RecipesLazyRoute = RecipesLazyImport.update({
  path: "/recipes",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/recipes.lazy").then((d) => d.Route))

const DiaryLazyRoute = DiaryLazyImport.update({
  path: "/diary",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/diary.lazy").then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const FoodsIndexLazyRoute = FoodsIndexLazyImport.update({
  path: "/foods/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/foods.index.lazy").then((d) => d.Route))

const FoodsFoodIdRoute = FoodsFoodIdImport.update({
  path: "/foods/$foodId",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/diary": {
      id: "/diary"
      path: "/diary"
      fullPath: "/diary"
      preLoaderRoute: typeof DiaryLazyImport
      parentRoute: typeof rootRoute
    }
    "/recipes": {
      id: "/recipes"
      path: "/recipes"
      fullPath: "/recipes"
      preLoaderRoute: typeof RecipesLazyImport
      parentRoute: typeof rootRoute
    }
    "/foods/$foodId": {
      id: "/foods/$foodId"
      path: "/foods/$foodId"
      fullPath: "/foods/$foodId"
      preLoaderRoute: typeof FoodsFoodIdImport
      parentRoute: typeof rootRoute
    }
    "/foods/": {
      id: "/foods/"
      path: "/foods"
      fullPath: "/foods"
      preLoaderRoute: typeof FoodsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DiaryLazyRoute,
  RecipesLazyRoute,
  FoodsFoodIdRoute,
  FoodsIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/diary",
        "/recipes",
        "/foods/$foodId",
        "/foods/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/diary": {
      "filePath": "diary.lazy.tsx"
    },
    "/recipes": {
      "filePath": "recipes.lazy.tsx"
    },
    "/foods/$foodId": {
      "filePath": "foods.$foodId.tsx"
    },
    "/foods/": {
      "filePath": "foods.index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
